### ISSUE TITLE
Spam Error

### ISSUE THREAD

**Issue by MatinDark** [Photon-GitHub/AACAdditionPro#234] opened 2018-06-03 21:10 UTC
Please include:
- Server version: 1.12.2 paperspigot
- ProtocolLib version: 4.4.0 
- The version of AACAdditionPro: 3.13.1 
- A detailed description of the bug / wanted feature: spamming error :
`
[01:39:20 WARN]: [AACAdditionPro] Task #139340 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #177870 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #301832 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #139340 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #177870 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #301832 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #139340 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #177870 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #301832 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #139340 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #177870 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #301832 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAdditionPro] Task #139340 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
[01:39:20 WARN]: [AACAd`

**Comment by andrewkm** [comment] 2018-06-04 15:43
Looks like this, and my issue are the same/related:
https://github.com/Photon-GitHub/AACAdditionPro/issues/235

**Comment by Photon-GitHub** [comment] 2018-06-05 20:34
Duplicate of #235 . I keep the newer issue open as it offers more detail.

**Closed by Photon-GitHub** 2018-06-05 20:34 UTC
Labels: 1. error, 4. duplicate
