### ISSUE TITLE
Log spam 5 times per second: Cannot measure distance between two worlds

### ISSUE THREAD

**Issue by MedicOP** [Photon-GitHub/AACAdditionPro#40] opened 2017-03-25 13:55 UTC
```java
[09:55:00 WARN]: [AACAdditionPro] Task #31 for AACAdditionPro v1.4.2 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and sg
        at org.bukkit.Location.distanceSquared(Location.java:456) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at de.photon.AACAdditionPro.b.a.d.e(Unknown Source) ~[?:?]
        at de.photon.AACAdditionPro.b.a.d$$Lambda$21/769474607.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-5073b0f-07c3001]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by Janmm14** [comment] 2017-03-25 14:30
Duplicate of #36

**Closed by Janmm14** 2017-03-25 14:30 UTC
Labels: duplicate, error
