### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro

### ISSUE THREAD

**Issue by MatheweB** [Photon-GitHub/AACAdditionPro#106] opened 2017-07-14 16:25 UTC
I relieve this error every time somebody logs into the server/at random:

14.07 12:23:55 [Server] ERROR [AACAdditionPro] Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro
14.07 12:23:55 [Server] INFO java.util.ConcurrentModificationException: null
14.07 12:23:55 [Server] INFO at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_121]
14.07 12:23:55 [Server] INFO at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_121]
14.07 12:23:55 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getEntities(CraftWorld.java:621) ~[spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at de.photon.AACAdditionPro.f.j.b.b(Unknown Source) ~[AACAdditionPro_2.0.3.jar:?]
14.07 12:23:55 [Server] INFO at de.photon.AACAdditionPro.b.a.p.onPacketReceiving(Unknown Source) ~[AACAdditionPro_2.0.3.jar:?]
14.07 12:23:55 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.3.0]
14.07 12:23:55 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.3.0]
14.07 12:23:55 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.3.0]
14.07 12:23:55 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.3.0]
14.07 12:23:55 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.3.0]
14.07 12:23:55 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.3.0]
14.07 12:23:55 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:531) [ProtocolLib.jar:4.3.0]
14.07 12:23:55 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
14.07 12:23:55 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
14.07 12:23:55 [Server] ERROR Parameters: 
14.07 12:23:55 [Server] INFO net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook@23cc6e78[
14.07 12:23:55 [Server] INFO x=-322.4770045250311
14.07 12:23:55 [Server] INFO y=80.0
14.07 12:23:55 [Server] INFO z=-253.0207045526537
14.07 12:23:55 [Server] INFO yaw=8.525452
14.07 12:23:55 [Server] INFO pitch=33.371494
14.07 12:23:55 [Server] INFO f=false
14.07 12:23:55 [Server] INFO hasPos=true
14.07 12:23:55 [Server] INFO hasLook=true
14.07 12:23:55 [Server] INFO ]

Please fix this!

**Comment by Photon-GitHub** [comment] 2017-07-14 18:17
Duplicate of #99

**Closed by Photon-GitHub** 2017-07-14 18:17 UTC
Labels: duplicate, error
