### ISSUE TITLE
New feature for Heuristic-Addition

### ISSUE THREAD

**Issue by Toshka17** [Photon-GitHub/AACAdditionPro#216] opened 2018-04-26 21:25 UTC
Some patterns for Heuristic check give a lot of false positives.
It would be very cool if you added the ability to create different "confidences" tresholds for different patterns.

**Comment by Minemaniak** [comment] 2018-04-27 18:36
Duplicate https://github.com/Photon-GitHub/AACAdditionPro/issues/184

**Comment by Janmm14** [comment] 2018-04-27 18:51
Duplicate of #184

**Closed by Janmm14** 2018-04-27 18:51 UTC
Labels: 1. feature, 4. duplicate, 4. wontfix
