### ISSUE TITLE
KAEntity check performence issue&TPS Dropped

### ISSUE THREAD

**Issue by jiangdashao** [Photon-GitHub/AACAdditionPro#128] opened 2017-08-26 15:29 UTC
After I use AACAdditionPro,I found that sometimes server will be very lag,TPS even drop to 15 (50 players online)
So I use LagMonitor&Timings,I found that AACAdditionPro used 2+% time in mian thread,after I disable KAEitity,It just use 0.07%

I get this data in my own test server,I enable timings and combat&movement for few miniutes....
So I think if the server have more player online,the AACAdditionPro will use more time in mian thread,so that tps dropped.

**Comment by Photon-GitHub** [comment] 2017-08-26 16:36
Please append the full timings, your hardware info and general information that every issue should have.
KillauraEntity can be heavy as it has to simulate one fake player per real player, and 2% is not something I assess critical.

**Comment by jiangdashao** [comment] 2017-08-26 17:07
but 2% is when one player,and today my network have many servers tps dropped,this is the first time I use aacadditionpro.so I think your plugin cause lag

This is 20 players timings:
[timings2.txt](https://github.com/Photon-GitHub/AACAdditionPro/files/1253835/timings2.txt)

**Comment by Janmm14** [comment] 2017-08-26 22:17
Please use /timings paste for your timings data.
In case you get an invalid url, you need to update your spigot, in february (i guess) there was a new spigot 1.8.8 which fixes that timings command.

**Comment by Pokemonplatin** [comment] 2017-09-01 17:49
https://timings.spigotmc.org/?url=jimasucide as nothing is happening here is my log with bots on.
https://timings.spigotmc.org/?url=wulotejage this is a log where they are turned off, still some lag.

**Comment by Photon-GitHub** [comment] 2017-09-30 19:36
As I and many other users cannot reproduce this problem and the timings are no longer present I will close this. 3.2.4 will feature some improvements as of proper gamemode - change handling (creative and spectator players will no longer have entities that need to be processed), if they are not enough and you have more evidence do not hesitate to reopen.

**Closed by Photon-GitHub** 2017-09-30 19:36 UTC
Labels: bug, insufficient information
