### ISSUE TITLE
Bug in console. Objects

### ISSUE THREAD

**Issue by IvanMankov** [Photon-GitHub/AACAdditionPro#109] opened 2017-07-16 03:17 UTC
**Spigot 1.12, AAC 3.2.1 (the latest), AACPro 3.0.0**

It is very often appears:

```
[06:12:01 WARN]: [AACAdditionPro] Task #251314 for AACAdditionPro v3.0.0-SNAPSHOT generated an exception
java.lang.IllegalArgumentException: You cannot register objects without a watcher object!                                            
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:396) ~[?:?]                          
        at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:406) ~[?:?]                          
        at de.photon.AACAdditionPro.f.b.c.b(Unknown Source) ~[?:?]                                                                   
        at de.photon.AACAdditionPro.b.a.r.a(Unknown Source) ~[?:?]                                                                   
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-7228328-6659ddf]  
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git
-Spigot-7228328-6659ddf]                                                                                                             
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]    
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]    
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]    
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]  
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by Photon-GitHub** [comment] 2017-07-16 12:01
Duplicate of #108

**Closed by Photon-GitHub** 2017-07-16 12:01 UTC
Labels: duplicate, error
