### ISSUE TITLE
AACAdditionPro is sending a completely empty packet (which is not allowed).

### ISSUE THREAD

**Issue by andrewkm** [Photon-GitHub/AACAdditionPro#214] opened 2018-04-12 01:14 UTC
### Issue description

Long time issue that finally got so annoying, I've spent an hour tracking down.
At first it was reported here:
https://github.com/SpigotMC/BungeeCord/issues/2399

I then decided to do some heavy digging.

Going through all my server,bungee,changes,other logs, for a good hour, I've finally tracked down this bungee issue being 100% AACAdditionPro related.

Basically, randomly players are disconnected from the server and this is due to, quoting @md-5 "the server sending a completely empty packet (which is not allowed)"

To attempt to assist in tracking this problem down, here is our latest occurrence:

Earlier today, 19:10:55 Eastern Time
Bungee Error: https://pastebin.com/raw/7uZWFdBC (Player dropped from server)

Earlier today, 19:10:55 Eastern Time
Corresponding AACAdditionPro Log: https://pastebin.com/raw/Gt2PvqLj (Player dropped from server)

Full logs of that player around that time frame expanding back for a few hours:
https://pastebin.com/raw/d5U2e4fj

I can confirm this happens to totally clean clients, including my own client which is not modified in any way. It also happens as I stay absolutely still AFK'ing away from my computer.

If you need any other help tracking this let me know. Thanks.

### Core information
**Server version**: 1.12.2 - Spigot Build 1545

**AAC version**: 3.3.14
**AAC config**: 3.3.13|1-Default-Celebrimbor

**AACAdditionPro version**: 3.11.1
**AACAdditionPro config**: 3.11.0|1-Default-Celebrimbor

**ProtocolLib version**: 4.3.0 Build 390

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Janmm14** [comment] 2018-04-12 11:07
Which modules of AACAdditionPro are you using?

**Comment by andrewkm** [comment] 2018-04-12 11:10
Meaning?

**Comment by Janmm14** [comment] 2018-04-12 17:04
What is enabled in config and what is disabled?

**Comment by md-5** [comment] 2018-05-15 22:33
No, the packet doesn't even contain a type (that's why its empty).

**Comment by Janmm14** [comment] 2018-05-16 07:08
AACAdditionPro is "just" using protocollib to modify / cancel / insert packets into the packet stream.
I guess there is some underlying issue in either ProtocolLib or multiprotocol plugins, maybe combined with asynchronous special events.
To get to the ground of that issue, one would likely have to modify / proxy all packet stream insertions and handlers to check for packet length.

**Comment by Photon-GitHub** [comment] 2018-10-10 18:42
@andrewkm This might be fixed in 3.4.0 as I updated a lot of the suspicious code.

**Comment by PsychoLynx** [comment] 2019-01-06 08:57
Hello!

Not sure if this is related, but I was also getting random player kicks from empty packets using Waterfall as proxy when players were opening containers and taking stuff out from containers (chests, furnaces). 

After testing I am fairly certain that this was caused by AACAP's inventory check, as disabling the check eliminated the problem. The two messages that seem related to the problem are:

Inventory-Verbose | Player: X moved while having an open inventory.
Inventory-Verbose | Player: X sent new rotations while having an open inventory.

**Closed** 2020-04-18 18:42 UTC
Labels: 1. error, 3. recheck newest version
