### ISSUE TITLE
Could not pass event PlayerInteractEvent to AACAdditionPro v5.1.0

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#315] opened 2019-04-14 14:52 UTC
log
https://pastebin.com/C3ZuqChG
i use paper spigot 1.12.2
aac latest version
viaversion

**Comment by Photon-GitHub** [comment] 2019-04-18 01:14
Duplicate of #314

**Closed by Photon-GitHub** 2019-04-18 01:14 UTC
Labels: 1. error
