### ISSUE TITLE
Inventory Move Bug & Freecam teleport debug messages

### ISSUE THREAD

**Issue by SnakeDaoust1232** [Photon-GitHub/AACAdditionPro#80] opened 2017-05-17 20:49 UTC
Info: 
- While sprinting, if you stop sprinting, open your inventory, and spam click in your inventory as you land, you get flagged for inventory move. As well, instead of setting you back, it kicks you from the server.
(Kick Message: https://gyazo.com/c2a6fca1f984937b4f03541a65ce1cba)
- Debug messages: https://gyazo.com/b167544ee5aa3dcb074239ef63a99231

Video: https://www.youtube.com/watch?v=is9cErlHlaM&feature=youtu.be

Inventory move Config: https://hastebin.com/zepepasise.bash

Core information

Server version: Paperspigot 1.8.8
AAC version: 3.1.6b4
AACAdditionPro Version: 1.9.2
ProtocolLib version: 4.2.1
Plugin list: (Upon request)

Special environment information

ViaVersion version: 1.0.4
ProtocolSupport version: 4.24
BungeeCord plugins: (Upon request)

**Comment by Photon-GitHub** [comment] 2017-05-19 14:25
The question is: Is this caused by my plugin or by AAC :/

**Comment by SnakeDaoust1232** [comment] 2017-05-28 16:20
Not sure actually. Does AAC do anything with inventories that could be causing it?

**Comment by konsolas** [comment] 2017-06-04 10:12
This should be closed because the debug message was part of AAC, and has since been removed.

@Photon-GitHub

**Comment by Photon-GitHub** [comment] 2017-06-09 17:07
Closed as of konsolas' message.

**Closed by Photon-GitHub** 2017-06-09 17:07 UTC
Labels: bug
