### ISSUE TITLE
Join=Error

### ISSUE THREAD

**Issue by MCFeelBoyYT** [Photon-GitHub/AACAdditionPro#131] opened 2017-08-27 11:39 UTC
Hello I have a problem, when a Player join this error message come.

https://pastebin.com/cRY7B7BK

**Comment by Photon-GitHub** [comment] 2017-08-28 21:21
Duplicate of #108 
If you want to solve this you have to disable the KillauraEntity check.

**Closed by Photon-GitHub** 2017-08-28 21:21 UTC
Labels: duplicate, error
