### ISSUE TITLE
Error AACAP 4.6.2 | Task null

### ISSUE THREAD

**Issue by AlxC01** [Photon-GitHub/AACAdditionPro#302] opened 2019-01-03 12:50 UTC
Hello!

I'm having some problems with the AACAP, I miss some errors in the sense and ejects some jurors "randomly" I imagine that all this happens because of the errors of the console. I hope you can tell me some kind of solution.

Server version: PapperSpigot 1.8.8
ProtocolLib version: 4.4.0-SNAPSHOT-b403
AACAP version: 4.6.2
Logs: https://pastebin.com/vPkQ6NeC

A greeting

**Comment by Photon-GitHub** [comment] 2019-01-03 14:31
Duplicate of #299

**Closed by Photon-GitHub** 2019-01-03 14:31 UTC
