### ISSUE TITLE
AAC+ kicking wrong player

### ISSUE THREAD

**Issue by Justinis77** [Photon-GitHub/AACAdditionPro#101] opened 2017-06-28 12:54 UTC
Hello, i want to Block Forge with AACkick but this is not Working.

[17:11:01] [Server thread/INFO]: brotan69[/--- logged in with entity id 1196 at ([hub2]82.50201065646162, 41.0, 9.313117898831795)
[17:11:02] [Server thread/INFO]: Killstreak891 is not online.
[17:11:02] [Server thread/INFO]: /aackick [player] [reason]

brotan have Forge but AACaddition is trying to kick a Random player

Version: AAC 3.1.6 b5
AACAdditionPro: 2.0.2
Server version: Spigot 1.8.8

   Forge:
      # Do you want to enable the Forge-Control
      # This cannot be blocked; I recommend to kick if desired
      enabled: true
      commands_on_detection:
         - "aackick {player} \u00a7cDu wurdest vom Netzwerk gekickt!\n \u00a73Grund\u00a78: \u00a7eUnerlaubte Modifikation"

**Comment by CeIebrimbor** [comment] 2017-06-28 14:06
@Photon-GitHub 
This is the 4th case I've seen (3rd server) where AACaddition is detecting a hacker and kicking a random player, generally someone who isn't even online. I saw one example of AAC+ trying to kick a player that hadn't been on in 24 hours.

**Comment by Justinis77** [comment] 2017-07-04 18:33
pls fix

**Comment by SnakeDaoust1232** [comment] 2017-07-08 17:36
@CeIebrimbor Me to. I get random notifications in console.

**Comment by Photon-GitHub** [comment] 2017-07-14 18:16
Fixed in 3.0.0

**Comment by Justinis77** [comment] 2017-07-14 18:17
thx

**Comment by Justinis77** [comment] 2017-07-26 18:50
this is not Fixed pls open this

**Comment by CeIebrimbor** [comment] 2017-07-26 20:01
@Justinis
See #111

**Comment by Hyronymos** [comment] 2018-03-24 22:03
reopen pls

**Comment by Photon-GitHub** [comment] 2018-03-28 19:04
This is most likely not caused by my plugin as I am only parsing the player from AAC's PlayerViolationEvent.

**Comment by Photon-GitHub** [comment] 2018-05-15 16:16
I will close this for now as this is a problem of AAC.

**Closed by Photon-GitHub** 2018-05-15 16:16 UTC
Labels: 1. bug, 3. cannot reproduce, 3. critical
