### ISSUE TITLE
AAC+ // Tower False Positive // Critical

### ISSUE THREAD

**Issue by OWERLORD01** [Photon-GitHub/AACAdditionPro#50] opened 2017-04-07 13:45 UTC
## _False Positive // Description_
_Hi! I have false positive with tower!
When player in Gm1 or with fly is placing block in bottom, he got banned for tower!_
You can see more info in _[this video!](https://youtu.be/w6Ue7W6XGbk)_ Please fix it as soon as possible!

## Core Info

_AAC Version_ // **3.1.2** _(Latest)_
_AACAdditionPro_ // **1.6** _(Latest)_

## ViaVersion // ProtocolSupport // Spigot
My Server is running ProtocolSupport Build [#38](https://build.true-games.org/job/ProtocolSupport/38/) Im not running viaversion. 
My Spigot Version is TacoSpigot [#89](https://ci.techcable.net/job/TacoSpigot/89/), Im not running bungeecord!
## Thanks
Please fix it as soon as possible! Thanks!

**Comment by OWERLORD01** [comment] 2017-04-07 16:49
## Sorry
The issue was probably because i haven't reseted config...
Sorry for this :P

**Comment by OWERLORD01** [comment] 2017-04-08 13:38
Or not... this false positive is appearing again sometimes...

**Comment by Photon-GitHub** [comment] 2017-04-08 14:31
As long as the player is allowed to fly he is ignored by AACAdditionPro. Maybe some bad plugin of yours is causing this.

**Comment by Photon-GitHub** [comment] 2017-04-09 23:01
I will close this due to no answer and the high probability that this is not caused by my plugin.

**Closed by Photon-GitHub** 2017-04-09 23:01 UTC
Labels: bug, cannot reproduce

**Comment by MedicOP** [comment] 2017-04-15 18:55
Experiencing same problem, players are getting banned for Tower even though they are in Creative mode. 

```java
[10:16:24.269] MedicOP failed Tower | Vl: 15 | TPS: 20.0 | Ping: 22
[10:16:24.269] Tower-Verbose | Player: MedicOP expected time: 464.145 | real: 239.0
```

**Comment by MedicOP** [comment] 2017-04-15 18:56
Are you checking using allow-flight or flying?

**Comment by MedicOP** [comment] 2017-04-15 19:03
I can reproduce it 100% of the time, all you have to do is just build a tower while in creative mode and you will get kicked

**Comment by OWERLORD01** [comment] 2017-04-16 16:17
> I can reproduce it 100% of the time, all you have to do is just build a tower while in creative mode and you will get kicked

It looks like its fixed in the latest update? I'm not getting this fp again... Yey!
