### ISSUE TITLE
Unhandled exception executing command 'aacap' in plugin AACAdditionPro v4.1.0

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#264] opened 2018-08-13 19:45 UTC
Please include:
- Server version: paper spigot 1.12.2
- ProtocolLib version: 4.4.0
- The version of AACAdditionPro: 4.1.0
- A detailed description of the bug / wanted feature: i can't do /aacap on game
- If possible a short video of the bug: 
DOWNLOAD LOG (use notepad++)
https://drive.google.com/open?id=1zJMh-kJBfEWAQBOUMqrtdKsuS9w-7WL9

**Comment by Photon-GitHub** [comment] 2018-08-13 19:56
Duplicate of #263

**Closed by Photon-GitHub** 2018-08-13 19:56 UTC
