### ISSUE TITLE
Error: https://hastebin.com/ehifurigaj.css

### ISSUE THREAD

**Issue by Felix5566** [Photon-GitHub/AACAdditionPro#68] opened 2017-04-27 14:57 UTC
Please fix the consol spam: https://hastebin.com/ehifurigaj.css

Version:
Server: Spigot 1.8.8
AAC: 3.1.5
AACAdditionPro: 1.8.2
ProtocolLob: 4.2.1

**Comment by Janmm14** [comment] 2017-04-27 15:08
Please go to the start of your log file, there the full error can be seen

**Comment by Felix5566** [comment] 2017-04-27 15:10
this is the full error

**Comment by Janmm14** [comment] 2017-04-27 15:18
No, because java removes useful information if an execption occurrs often to reduce computing time.

**Comment by Felix5566** [comment] 2017-04-27 18:43
sorry, yes: https://hastebin.com/afonexocol.css

**Comment by Photon-GitHub** [comment] 2017-04-29 16:28
Duplicate of #66

**Closed by Photon-GitHub** 2017-04-29 16:28 UTC
Labels: error
