### ISSUE TITLE
KillAuraEntity not working + error in console when someone joins

### ISSUE THREAD

**Issue by AndGK** [Photon-GitHub/AACAdditionPro#130] opened 2017-08-26 22:18 UTC
Hey. Kill aura entity is not working completely. I get a console error sometimes and some of my players complain that if they do not log out for a while, they can see a lot of random nicknames in the tab for no reason (not deleted NPCs; not a clue how if they don't spawn at all).

The error:
```
[17:59:06] [Server thread/INFO]: AndGK[/99.224.181.151:55302] logged in with entity id 2762462 at ([world]1.9705017125690594, 67.5, -59.29174932051792)
[17:59:06] [Server thread/WARN]: [AACAdditionPro] Task #3442921 for AACAdditionPro v3.2.1 generated an exception
java.lang.IllegalArgumentException: You cannot register objects without a watcher object!
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:396) ~[ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:406) ~[ProtocolLib.jar:4.3.0]
	at de.photon.AACAdditionPro.aG.b(aG.java) ~[AACAdditionPro-3.2.1.jar:?]
	at de.photon.AACAdditionPro.I.lambda$null$0(I.java) ~[AACAdditionPro-3.2.1.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by ItzSomebody** [comment] 2017-08-26 22:32
What ProtocolLib version are you using?

**Comment by AndGK** [comment] 2017-08-26 23:53
4.3.0

**Comment by Photon-GitHub** [comment] 2017-08-27 00:07
Duplicate of #108

**Closed by Photon-GitHub** 2017-08-27 00:07 UTC
