### ISSUE TITLE
NullPointer (java.lang.NoSuchMethodError) v5.1.1

### ISSUE THREAD

**Issue by Noahkemm** [Photon-GitHub/AACAdditionPro#320] opened 2019-04-29 15:34 UTC
`Could not pass event PlayerInteractEvent to AACAdditionPro v5.1.1`

https://paste.mykns.net/dujohubozu.vbs

**Comment by Photon-GitHub** [comment] 2019-04-29 18:59
Duplicate of #318

**Closed by Photon-GitHub** 2019-04-29 18:59 UTC
