### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by AixMC** [Photon-GitHub/AACAdditionPro#382] opened 2020-02-15 16:37 UTC
I am getting this error on every Player Join 

latest Paperspigot and Waterfall, no ProtocolSupport or ViaVersion

https://hastebin.com/uwewalacim.rb

**Comment by Photon-GitHub** [comment] 2020-02-21 16:10
Hastebin doesn't show anything to me. Please use a service with persistent data, like pastebin.

**Comment by Photon-GitHub** [comment] 2020-02-21 16:10
Also, please include your minecraft / server version. "Latest" is not a valid reason at that can change quickly.

**Comment by Janmm14** [comment] 2020-02-21 21:03
I was able to retrieve the hastebin data surprisingly:
```
[15.02 17:31:29.166] INFO: Login from identity 2c7e81f4-2a12-49ad-a2f9-78e73303cbf4:Daten on Minecraftserver Lobby-1 was successful
[15.02 17:31:29.181] INFO: [Lobby-1] [17:31:29 INFO]: [AAC] 1.15 detected for Daten
[15.02 17:31:29.483] INFO: [Lobby-1] [17:31:29 WARN]: [ProtocolLib] Loaded class de.photon.aacadditionpro.util.packetwrappers.server.WrapperPlayServerNamedEntitySpawn from AACAdditionPro v6.0.4 which is not a depend, softdepend or loadbefore of this plugin.
[15.02 17:31:29.484] INFO: [Lobby-1] [17:31:29 ERROR]: [AACAdditionPro] Unhandled exception occured in onPacketSending(PacketEvent) for AACAdditionPro
[15.02 17:31:29.484] INFO: [Lobby-1] com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_15_R1.DataWatcher exists in class PacketPlayOutNamedEntitySpawn.
[15.02 17:31:29.485] INFO: [Lobby-1]    at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[?:?]
[15.02 17:31:29.507] INFO: [Lobby-1]    at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
[15.02 17:31:29.508] INFO: [Lobby-1]    at de.photon.aacadditionpro.util.packetwrappers.server.WrapperPlayServerNamedEntitySpawn.getMetadata(WrapperPlayServerNamedEntitySpawn.java:178) ~[?:?]
[15.02 17:31:29.508] INFO: [Lobby-1]    at de.photon.aacadditionpro.modules.clientcontrol.DamageIndicator.onPacketSending(DamageIndicator.java:120) ~[?:?]
[15.02 17:31:29.508] INFO: [Lobby-1]    at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
[15.02 17:31:29.520] INFO: [Lobby-1]    at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
[15.02 17:31:29.520] INFO: [Lobby-1]    at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
[15.02 17:31:29.521] INFO: [Lobby-1]    at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
[15.02 17:31:29.522] INFO: [Lobby-1]    at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
[15.02 17:31:29.522] INFO: [Lobby-1]    at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
[15.02 17:31:29.522] INFO: [Lobby-1]    at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
[15.02 17:31:29.522] INFO: [Lobby-1]    at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
[15.02 17:31:29.523] INFO: [Lobby-1]    at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
[15.02 17:31:29.523] INFO: [Lobby-1]    at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
[15.02 17:31:29.523] INFO: [Lobby-1]    at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
[15.02 17:31:29.523] INFO: [Lobby-1]    at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
[15.02 17:31:29.524] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.NetworkManager.b(NetworkManager.java:200) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.524] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.524] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1542) ~[?:git-Paper-105]
[15.02 17:31:29.524] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.PlayerConnection.sendPacket(PlayerConnection.java:1515) ~[?:git-Paper-105]
[15.02 17:31:29.525] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:276) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.532] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:260) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.536] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1716) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.536] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:1575) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.536] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:1050) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.537] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:1323) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.542] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1460) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.542] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.ChunkProviderServer.addEntity(ChunkProviderServer.java:819) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.543] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.WorldServer.registerEntity(WorldServer.java:1414) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.543] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.WorldServer.addPlayer0(WorldServer.java:1179) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.543] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.WorldServer.addPlayerJoin(WorldServer.java:1155) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.543] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:230) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.544] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.544] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.544] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.545] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.545] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.545] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.550] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.551] INFO: [Lobby-1]    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[paper.jar:git-Paper-105]
[15.02 17:31:29.556] INFO: [Lobby-1]    at java.lang.Thread.run(Thread.java:834) [?:?]
[15.02 17:31:29.556] INFO: [Lobby-1] [17:31:29 ERROR]: Parameters: 
[15.02 17:31:29.556] INFO: [Lobby-1]   net.minecraft.server.v1_15_R1.PacketPlayOutNamedEntitySpawn@4586d1e0[
[15.02 17:31:29.557] INFO: [Lobby-1]     a=313
[15.02 17:31:29.557] INFO: [Lobby-1]     b=13230236-fee8-4d39-85a8-c1203ef3b234
[15.02 17:31:29.557] INFO: [Lobby-1]     c=18.928313321429258
[15.02 17:31:29.563] INFO: [Lobby-1]     d=72.0
[15.02 17:31:29.563] INFO: [Lobby-1]     e=11.76875793307651
[15.02 17:31:29.563] INFO: [Lobby-1]     f=60
[15.02 17:31:29.563] INFO: [Lobby-1]     g=6
[15.02 17:31:29.564] INFO: [Lobby-1]   ]
```

**Comment by Photon-GitHub** [comment] 2020-02-21 21:51
Duplicate of #370

**Closed by Photon-GitHub** 2020-02-21 21:51 UTC
Labels: 1. error
