### ISSUE TITLE
Massive TPS loss over time

### ISSUE THREAD

**Issue by Cryptite** [Photon-GitHub/AACAdditionPro#399] opened 2020-05-21 14:40 UTC
Hard to say why this happens, but some combination of AACAP, possibly Holographic Displays and unloading chunks leads to a massive TPS drop after awhile. Here's a profiling capture of what it looks like.

![image](https://user-images.githubusercontent.com/399721/82570369-1b3a2480-9b47-11ea-90be-486fc7336367.png)

**Comment by Photon-GitHub** [comment] 2020-05-21 20:45
The playerinformationmodifier is a part of ESP, which is a pretty heavy check, especially on more recent versions of minecraft. If your player count has gone up or all your players have come close to each other for some reason, ESP will start to lag as the computational effort is proportional to the squared player count (which cannot be avoided). Can you confirm that player count was (mostly) stable? I already know of the problems and will try to partially address them in the next major version, but a quite some part of the lag is caused by the poor optimization of the more recent minecraft versions.

**Comment by Cryptite** [comment] 2020-05-21 21:17
Unless Citizens (the plugin) has a part to play here, this happens with only 1 player online eventually.

**Comment by Cryptite** [comment] 2020-05-22 20:26
I should also mention we have (and had at that profiling report) Esp off...

**Comment by Photon-GitHub** [comment] 2020-05-23 18:49
Well, that promises to get interesting then.

**Comment by Photon-GitHub** [comment] 2020-05-23 20:56
Should be fixed (or at least improved) in the upcoming version.

**Closed** 2020-07-09 15:11 UTC
Labels: 1. bug, 2. performance, 4. fixed
