### ISSUE TITLE
Spammed console when new player joins and disconnects

### ISSUE THREAD

**Issue by CypherPhyre** [Photon-GitHub/AACAdditionPro#245] opened 2018-07-13 13:17 UTC
Please include:
- Server version: Spigot 1.12.2
- ProtocolLib version: v4.4.0-SNAPSHOT-b392
- The version of AACAdditionPro: v3.13.1
- A detailed description of the bug / wanted feature: 

I woke up to the following spamming my console.

This log snippet starts at line 76 and ran to line 1598889 before I restarted the server.

I only have this issue when it is a new player (first-time join)

[06:14:32] [User Authenticator #1/INFO]: UUID of player diamondminer77 is f3440052-4923-4b2e-960e-6b0dece36b89
[06:14:33] [Netty Epoll Server IO #2/ERROR]: java.lang.NullPointerException
[06:14:33] [Netty Epoll Server IO #2/ERROR]: java.lang.NullPointerException
[06:14:33] [Server thread/INFO]: [eZProtector] The SmartMoving block is currently not available.
[06:14:33] [Server thread/INFO]: [0;33;1mWelcome [0;33;22mdiamondminer77 [0;33;1mto [21m[0;34;1mCOBBLE[0;32;1mForest [3m[4m[0;36;1mNext Generation![m
[06:14:33] [Server thread/INFO]: diamondminer77[/173.239.210.6:58838] logged in with entity id 10157 at ([world]-575.5225330164662, 146.0, -874.220298970979)
[06:14:33] [Server thread/INFO]: diamondminer77 lost connection: Disconnected
[06:14:36] [Server thread/INFO]: diamondminer77 left the game
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419435 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.Q.lambda$null$0(Q.java:13) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419440 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.bn.b(bn.java:121) ~[AACAdditionPro-3.13.1.jar:?]
	at de.photon.AACAdditionPro.bo.b(bo.java:95) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419447 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.Q.lambda$null$0(Q.java:13) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/INFO]: [AAC] [VERBOSE] (TPSManager) TPS dropped to 6.753334458889077
[06:14:37] [Server thread/INFO]: [AAC] [VERBOSE] (CheckManager) Disabled check movement.BadPackets
[06:14:37] [Server thread/INFO]: [AAC] [VERBOSE] (CheckManager) Disabled check combat.FightSpeed
[06:14:37] [Server thread/INFO]: [AAC] [VERBOSE] (CheckManager) Disabled check world.NoSwing
[06:14:37] [Server thread/INFO]: [AAC] [VERBOSE] (CheckManager) Disabled check combat.Hitbox
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419440 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.bn.b(bn.java:121) ~[AACAdditionPro-3.13.1.jar:?]
	at de.photon.AACAdditionPro.bo.b(bo.java:95) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419448 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.bn.b(bn.java:121) ~[AACAdditionPro-3.13.1.jar:?]
	at de.photon.AACAdditionPro.bo.b(bo.java:95) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419440 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.bn.b(bn.java:121) ~[AACAdditionPro-3.13.1.jar:?]
	at de.photon.AACAdditionPro.bo.b(bo.java:95) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419448 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.bn.b(bn.java:121) ~[AACAdditionPro-3.13.1.jar:?]
	at de.photon.AACAdditionPro.bo.b(bo.java:95) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419466 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.Q.lambda$null$0(Q.java:13) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419440 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.bn.b(bn.java:121) ~[AACAdditionPro-3.13.1.jar:?]
	at de.photon.AACAdditionPro.bo.b(bo.java:95) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419448 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.bn.b(bn.java:121) ~[AACAdditionPro-3.13.1.jar:?]
	at de.photon.AACAdditionPro.bo.b(bo.java:95) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419467 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.bn.b(bn.java:121) ~[AACAdditionPro-3.13.1.jar:?]
	at de.photon.AACAdditionPro.bo.b(bo.java:95) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419440 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.bn.b(bn.java:121) ~[AACAdditionPro-3.13.1.jar:?]
	at de.photon.AACAdditionPro.bo.b(bo.java:95) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419448 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.bn.b(bn.java:121) ~[AACAdditionPro-3.13.1.jar:?]
	at de.photon.AACAdditionPro.bo.b(bo.java:95) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[06:14:37] [Server thread/WARN]: [AACAdditionPro] Task #11419467 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null

**Comment by Photon-GitHub** [comment] 2018-07-20 23:38
Might be fixed in 4.0.0 due to the huge KillauraEntity changes.

**Comment by Photon-GitHub** [comment] 2018-07-20 23:39
Duplicate of #244

**Closed by Photon-GitHub** 2018-07-20 23:39 UTC
Labels: 1. error
