### ISSUE TITLE
Error again and again and again....

### ISSUE THREAD

**Issue by campzazathelord** [Photon-GitHub/AACAdditionPro#98] opened 2017-06-14 13:31 UTC
https://pastebin.com/WU3mYCJT

latest everything
spigot: 188

**Comment by Photon-GitHub** [comment] 2017-06-14 14:27
Please look up other issues before posting. This prevents duplicates.

**Comment by Photon-GitHub** [comment] 2017-06-14 14:27
Duplicate of #97

**Closed by Photon-GitHub** 2017-06-14 14:27 UTC
Labels: duplicate, error
