### ISSUE TITLE
Player move backwords somtime

### ISSUE THREAD

**Issue by Felix5566** [Photon-GitHub/AACAdditionPro#75] opened 2017-05-07 22:20 UTC
Here: https://hastebin.com/ucoleleleh.css

**Versions**:
AAC: 3.1.6 (latest from May 1, 2017)
AACAdditionPro: 1.9.1 (latest)
ProtocolLib: 4.2.0
Server: 1.8.8

**Comment by Photon-GitHub** [comment] 2017-05-08 04:47
Duplicate of #74

**Closed** 2017-05-08 04:47 UTC
Labels: duplicate, error
