### ISSUE TITLE
Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro

### ISSUE THREAD

**Issue by andrewkm** [Photon-GitHub/AACAdditionPro#212] opened 2018-04-09 22:12 UTC
### Issue description

Console throwing:
https://pastebin.com/raw/1fPAHNU2

### Core information
**Server version**: 1.12.2 - Spigot Build 1545

**AAC version**: 3.3.14
**AAC config**: 3.3.13|1-Default-Celebrimbor

**AACAdditionPro version**: 3.11.1
**AACAdditionPro config**: 3.11.0|1-Default-Celebrimbor

**ProtocolLib version**: 4.3.0 Build 390

**Plugin list**: (on request via Discord - andrewkm-1759)

### Special environment information

**ViaVersion version**: none

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by Photon-GitHub** [comment] 2018-04-10 04:46
Duplicate of #208

**Closed by Photon-GitHub** 2018-04-10 04:46 UTC
