### ISSUE TITLE
Tried of the same error again and again and again

### ISSUE THREAD

**Issue by campzazathelord** [Photon-GitHub/AACAdditionPro#100] opened 2017-06-25 10:32 UTC
```[04:02:14] [Server thread/INFO]: [0;33;22mUptime:[0;31;1m 45 seconds[m
[04:02:14] [Server thread/INFO]: [0;33;22mCurrent TPS = [0;32;1m20[m
[04:02:14] [Server thread/INFO]: [0;33;22mMaximum memory:[0;31;1m 4,530 MB.[m
[04:02:14] [Server thread/INFO]: [0;33;22mAllocated memory:[0;31;1m 2,231 MB.[m
[04:02:14] [Server thread/INFO]: [0;33;22mFree memory:[0;31;1m 1,319 MB.[m
[04:02:14] [Server thread/INFO]: [0;33;22mWorld "[0;31;1mworld[0;33;22m": [0;31;1m320[0;33;22m chunks, [0;31;1m100[0;33;22m entities, [0;31;1m44[0;33;22m tiles.[m
[04:02:14] [Server thread/INFO]: [0;33;22mThe End "[0;31;1mworld_the_end[0;33;22m": [0;31;1m0[0;33;22m chunks, [0;31;1m0[0;33;22m entities, [0;31;1m0[0;33;22m tiles.[m
[04:02:14] [Server thread/INFO]: [0;33;22mWorld "[0;31;1mspawn[0;33;22m": [0;31;1m256[0;33;22m chunks, [0;31;1m206[0;33;22m entities, [0;31;1m171[0;33;22m tiles.[m
[04:02:14] [Server thread/INFO]: [0;33;22mNether "[0;31;1mworld_nether[0;33;22m": [0;31;1m0[0;33;22m chunks, [0;31;1m0[0;33;22m entities, [0;31;1m0[0;33;22m tiles.[m
[04:02:33] [Server thread/INFO]: Unknown command. Type "/help" for help.[m
[04:02:37] [Server thread/INFO]: [0;36;22m-------------([0;36;1m[21mYour Clearlag Commands[0;36;22m)-------------[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1mclear [0;37;1m -  (Clears entities from your worlds)[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1marea [0;37;1m -  (Clears entities from your radius)[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1mcheck [0;37;1m -  (Counts entities in your world(s))[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1mchunk [0;37;1m -  (Finds laggy chunks)[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1mgc [0;37;1m -  (Request garbage collecter)[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1mtps [0;37;1m -  (Checks the servers tick rate)[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1mkillmobs [0;37;1m -  (Clears mobs from your worlds)[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1mreload [0;37;1m -  (Reloads clearlag)[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1mtpchunk [0;37;1m -  (Teleport to chunks)[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1munloadchunks [0;37;1m -  (Unloads unused chunks)[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1mhalt [0;37;1m -  (Halts most server activity)[m
[04:02:37] [Server thread/INFO]:  [0;31;22m- [0;30;1m/[0;36;22mlagg [0;36;1madmin [0;37;1m -  (Control Clearlag's modules)[m
[04:02:37] [Server thread/INFO]: [0;36;22m----------------------------------------------------[m
[04:02:41] [Server thread/INFO]: [0;37;22m[21m[[0;34;22m[21mM[0;36;22m[21mC[0;31;22m-[0;35;1m[21mC[0;37;1m[21mo[0;32;1m[21mm[0;36;1m[21mp[0;33;1m[21ml[0;33;22m[21me[0;31;22m[21mx[0;31;1m[21mX[0;37;22m[21m] [0;32;22m[CONSOLE] [mlobby89 is suspected for AutoClicker (FightSpeed) (ping = 20, tps = 18.6) [m
[04:02:41] [Thread-147/INFO]: UUID of player VanjZi_PvP is 62fb56c1-85cb-34c5-b6e4-54ad8ccdc45a
[04:02:41] [Server thread/INFO]: VanjZi_PvP[/103.253.75.239:50242] logged in with entity id 1764 at ([spawn]290.5, 94.5, 237.5)
[04:02:42] [Server thread/INFO]: [0;33;22m[[0;32;1mClearLag[0;33;22m] [0;32;1m[0;36;1mYou just removed [0;36;22m11[0;36;1m entities![m
[04:02:46] [Server thread/INFO]: [0;33;22m[[0;32;1mClearLag[0;33;22m] [0;32;1m[0;36;22m264 [0;36;1mMobs have been removed![m
[04:02:47] [Craft Scheduler Thread - 4/INFO]: [Metrics] Server returned HTTP response code: 504 for URL: http://mcstats.org/report/CookieMonster
[04:02:53] [Server thread/INFO]: SpicelessNuggets issued server command: /spawn
[04:02:58] [Thread-149/INFO]: UUID of player 666 is 1ee79799-5aa3-3433-bd37-90203ecd5ce7
[04:02:58] [Server thread/INFO]: 666[/103.253.75.239:50251] logged in with entity id 2497 at ([spawn]290.5, 94.5, 237.5)
[04:03:12] [Server thread/INFO]: CommandBlock at 290,98,237 issued server command: /warp city8 VanjZi_PvP
[04:03:12] [Thread-150/INFO]: UUID of player eieixd is a30f3a94-bbbb-3f0b-92e2-7eba9a68f64c
[04:03:12] [Server thread/INFO]: eieixd[/103.253.75.239:50263] logged in with entity id 2680 at ([spawn]290.5, 94.5, 237.5)
[04:03:17] [Server thread/INFO]: CommandBlock at 296,98,233 issued server command: /warp city7 666
[04:03:18] [Async Chat Thread - #1/INFO]: [0;32;1m[Kingdow][m [m<[0;37;22mVIP: [0;34;1meieixd[0;33;1m พูดว่า:[m> หลุดป่ะ[m
[04:03:28] [Async Chat Thread - #1/INFO]: [0;32;1m[89][m [m<[0;37;22mVIP: [0;34;1mlobby89[0;33;1m พูดว่า:[m> หลุด[m
[04:03:28] [Server thread/INFO]: 666 issued server command: /Gun 
[04:03:30] [Server thread/INFO]: 666 issued server command: /Skill 
[04:03:32] [Server thread/INFO]: 666 issued server command: /shop 
[04:03:33] [Thread-151/INFO]: UUID of player jingjung123 is ad081453-1e35-397d-90f0-92b35b749473
[04:03:33] [Server thread/INFO]: jingjung123[/103.253.75.239:50284] logged in with entity id 3023 at ([spawn]290.5, 94.5, 237.5)
[04:03:41] [Server thread/INFO]: jingjung123 issued server command: /Gun 
[04:03:44] [Server thread/INFO]: [ServerSigns] execute Command: give jingjung123 267 1 
[04:03:44] [Server thread/INFO]: CONSOLE issued server command: /give jingjung123 267 1
[04:03:44] [Server thread/INFO]: [0;33;22mGiving[0;31;1m 1 [0;33;22mof[0;31;1m iron sword to[0;31;1m [0;37;22mGuest: [0;34;1mjingjung123[0;33;1m :พูดว่า:[m[0;33;22m.[m
[04:03:44] [Server thread/INFO]: [ServerSigns] execute Command: give jingjung123 322:1 5 
[04:03:44] [Server thread/INFO]: CONSOLE issued server command: /give jingjung123 322:1 5
[04:03:44] [Server thread/INFO]: [0;33;22mGiving[0;31;1m 5 [0;33;22mof[0;31;1m golden apple to[0;31;1m [0;37;22mGuest: [0;34;1mjingjung123[0;33;1m :พูดว่า:[m[0;33;22m.[m
[04:03:49] [Server thread/INFO]: jingjung123 issued server command: /shop 
[04:03:51] [Server thread/INFO]: eieixd issued server command: /shop 
[04:04:01] [Async Chat Thread - #1/INFO]: [0;32;1m[Kingdow][m [m<[0;37;22mVIP: [0;34;1meieixd[0;33;1m พูดว่า:[m> SpicelessNuggets[m
[04:04:01] [Server thread/INFO]: CommandBlock at 293,98,233 issued server command: /warp city6 jingjung123
[04:04:33] [Server thread/WARN]: [CookieMonster] Error rewarding player: unknown entity CraftRabbit{RabbitType=BLACK}
[04:04:52] [Server thread/INFO]: CONSOLE issued server command: /list 
[04:04:52] [Server thread/INFO]: [0;33;22mThere are [0;31;1m6[0;33;22m out of maximum [0;31;1m100[0;33;22m players online.[m
[04:04:52] [Server thread/INFO]: [0;33;22mmember[m: [m[0;37;22mGuest: [0;34;1m666[0;33;1m :พูดว่า:[m[0;37;1m, [0;37;22mGuest: [0;34;1mjingjung123[0;33;1m :พูดว่า:[m[0;37;1m, [0;37;22mGuest: [0;34;1mVanjZi_PvP[0;33;1m :พูดว่า:[m[0;37;1m[m
[04:04:52] [Server thread/INFO]: [0;33;22mVIP[m: [m[0;37;22mVIP: [0;34;1meieixd[0;33;1m พูดว่า:[m[0;37;1m, [0;37;22mVIP: [0;34;1mlobby89[0;33;1m พูดว่า:[m[0;37;1m, [0;37;22mVIP: [0;34;1mSpicelessNuggets[0;33;1m พูดว่า:[m[0;37;1m[m
[04:04:55] [Server thread/INFO]: 666 issued server command: /shop 
[04:05:03] [Server thread/INFO]: 666 issued server command: /shop 
[04:05:05] [Server thread/INFO]: 666 issued server command: /Skill 
[04:05:06] [Server thread/INFO]: 666 issued server command: /Gun 
[04:05:10] [Server thread/INFO]: VanjZi_PvP was slain by Zombie
[04:05:16] [Netty Server IO #1/ERROR]: [AACAdditionPro] Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_131]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getEntities(CraftWorld.java:626) ~[bukkit.jar:git-Spigot-db6de12-18fbb24]
	at de.photon.AACAdditionPro.f.j.b.b(Unknown Source) ~[AACAdditionPro_2.0.3.jar:?]
	at de.photon.AACAdditionPro.b.a.p.onPacketReceiving(Unknown Source) ~[AACAdditionPro_2.0.3.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.2.1]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.2.1]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.2.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[04:05:16] [Netty Server IO #1/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition@1d5bc604[
    x=443.2666033339754
    y=5.170787077218802
    z=1065.6421599438895
    yaw=0.0
    pitch=0.0
    f=false
    hasPos=true
    hasLook=false
  ]
```

**Comment by Janmm14** [comment] 2017-06-25 12:51
Duplicate of #99

**Closed by Janmm14** 2017-06-25 12:51 UTC
Labels: error
