### ISSUE TITLE
Getting thsis error

### ISSUE THREAD

**Issue by campzazathelord** [Photon-GitHub/AACAdditionPro#78] opened 2017-05-12 15:06 UTC
using the latest version of everything...
spigot 1.8.8
http://imgur.com/a/ytR6y

**Comment by Photon-GitHub** [comment] 2017-05-13 11:20
Please provide the full stacktrace.

**Comment by campzazathelord** [comment] 2017-05-13 14:02
thats all it shows. that error log... non stop

**Comment by campzazathelord** [comment] 2017-05-13 14:03
it keeps going on like that forever

**Comment by Janmm14** [comment] 2017-05-14 10:51
Go to your log file, search from the top for that error and it will be larger.

**Comment by campzazathelord** [comment] 2017-05-16 08:24
[03:46:11] [Craft Scheduler Thread - 11/INFO]: [Metrics] Unexpected end of file from server
[03:47:49] [Thread-122/INFO]: UUID of player CPXcAmp is 5dd15140-446b-31c4-8133-eff11b728529
[03:47:50] [Server thread/INFO]: CPXcAmp[/127.0.0.1:50764] logged in with entity id 33 at ([world]-819.5, 10.5, -263.5)
[03:47:52] [Server thread/INFO]: [ServerSigns] execute Command: pvpkit Samurai CPXcAmp 
[03:48:16] [Server thread/INFO]: CONSOLE issued server command: /list 
[03:48:16] [Server thread/INFO]: [0;33;22mThere are [0;31;1m1[0;33;22m out of maximum [0;31;1m100[0;33;22m players online.[m
[03:48:16] [Server thread/INFO]: [0;33;22mVip[m: [m[0;37;1m[21m[[0;36;22m[21mV[0;31;22m[21mI[0;35;22m[21mP[0;37;1m[21m][0;37;1mCPXcAmp[0;36;1m[m[0;37;1m[m
[03:48:17] [Server thread/INFO]: Unknown command. Type "/help" for help.[m
[03:48:17] [Server thread/INFO]: CONSOLE issued server command: /lag 
[03:48:17] [Server thread/INFO]: [0;33;22mUptime:[0;31;1m 2 minutes 21 seconds[m
[03:48:17] [Server thread/INFO]: [0;33;22mCurrent TPS = [0;32;1m19.74[m
[03:48:17] [Server thread/INFO]: [0;33;22mMaximum memory:[0;31;1m 9,102 MB.[m
[03:48:17] [Server thread/INFO]: [0;33;22mAllocated memory:[0;31;1m 1,241 MB.[m
[03:48:17] [Server thread/INFO]: [0;33;22mFree memory:[0;31;1m 903 MB.[m
[03:48:17] [Server thread/INFO]: [0;33;22mWorld "[0;31;1mworld[0;33;22m": [0;31;1m272[0;33;22m chunks, [0;31;1m11[0;33;22m entities, [0;31;1m190[0;33;22m tiles.[m
[03:48:17] [Server thread/INFO]: [0;33;22mThe End "[0;31;1mworld_the_end[0;33;22m": [0;31;1m0[0;33;22m chunks, [0;31;1m0[0;33;22m entities, [0;31;1m0[0;33;22m tiles.[m
[03:48:35] [Thread-133/INFO]: UUID of player poy is 32f34faa-cb9d-3cf0-b737-abbb5d0f0847
[03:48:35] [Server thread/INFO]: poy[/127.0.0.1:50790] logged in with entity id 34 at ([world]-819.5, 10.5, -263.5)
[03:48:36] [Server thread/WARN]: [AACAdditionPro] Task #52 for AACAdditionPro v1.8.2 generated an exception
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[?:1.8.0_77]
	at com.comphenix.protocol.reflect.StructureModifier.withType(StructureModifier.java:456) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.getItemSlots(PacketContainer.java:937) ~[?:?]
	at de.photon.AACAdditionPro.f.e.f.a(Unknown Source) ~[?:?]
	at de.photon.AACAdditionPro.f.i.a.a.c(Unknown Source) ~[?:?]
	at de.photon.AACAdditionPro.b.d.a.a(Unknown Source) ~[?:?]
	at de.photon.AACAdditionPro.b.d.a.e(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[bukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
[03:48:37] [Server thread/INFO]: [ServerSigns] execute Command: pvpkit EnderMage poy 
[03:48:37] [Server thread/WARN]: [AACAdditionPro] Task #52 for AACAdditionPro v1.8.2 generated an exception
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[?:1.8.0_77]
	at com.comphenix.protocol.reflect.StructureModifier.withType(StructureModifier.java:456) ~[?:?]
	at com.comphenix.protocol.events.PacketContainer.getItemSlots(PacketContainer.java:937) ~[?:?]
	at de.photon.AACAdditionPro.f.e.f.a(Unknown Source) ~[?:?]
	at de.photon.AACAdditionPro.f.i.a.a.c(Unknown Source) ~[?:?]
	at de.photon.AACAdditionPro.b.d.a.a(Unknown Source) ~[?:?]
	at de.photon.AACAdditionPro.b.d.a.e(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[bukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [bukkit.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
[03:48:42] [Async Chat Thread - #0/INFO]: [m<[0;37;1m[21m[[0;36;22m[21mV[0;31;22m[21mI[0;35;22m[21mP[0;37;1m[21m][0;37;1mCPXcAmp[0;36;1m[m> poy[m
[03:48:47] [Async Chat Thread - #0/INFO]: [m<[0;37;1m[21m[[0;36;22m[21mV[0;31;22m[21mI[0;35;22m[21mP[0;37;1m[21m][0;37;1mCPXcAmp[0;36;1m[m> มาตีหน่อย[m
[03:48:47] [Async Chat Thread - #0/INFO]: [m<[0;37;1m[21m[[0;32;22m[21mM[0;32;1m[21mE[0;32;22m[21mM[0;32;1m[21mB[0;32;22m[21mE[0;32;1m[21mR[0;37;1m[21m][0;37;1m[0;36;1mpoy[0;32;1m[m> ไร[m
[03:48:53] [Server thread/INFO]: [0;37;22m[[0;33;22mAAC[0;37;22m] [0;32;22m[CONSOLE] [mCPXcAmp is suspected for EqualRotation [m
[03:48:53] [Async Chat Thread - #0/INFO]: [m<[0;37;1m[21m[[0;32;22m[21mM[0;32;1m[21mE[0;32;22m[21mM[0;32;1m[21mB[0;32;22m[21mE[0;32;1m[21mR[0;37;1m[21m][0;37;1m[0;36;1mpoy[0;32;1m[m> ใหนอะ[m
[03:49:01] [Async Chat Thread - #0/INFO]: [m<[0;37;1m[21m[[0;36;22m[21mV[0;31;22m[21mI[0;35;22m[21mP[0;37;1m[21m][0;37;1mCPXcAmp[0;36;1m[m> ตีรัวๆ[m
[03:49:03] [Server thread/INFO]: [0;37;22m[[0;33;22mAAC[0;37;22m] [0;32;22m[CONSOLE] [mCPXcAmp is highly suspected for EqualRotation [m
[03:49:05] [Server thread/INFO]: [0;37;22m[[0;33;22mAAC[0;37;22m] [0;32;22m[CONSOLE] [mCPXcAmp is suspected for InventoryMove [m
[03:49:05] [Server thread/WARN]: CPXcAmp moved too quickly! 0.0,-18.613781637178043,0.0 (0.0, -18.613781637178043, 0.0)
[03:49:05] [Server thread/INFO]: CPXcAmp lost connection: Disconnected
[03:49:46] [Server thread/INFO]: poy lost connection: Disconnected
[03:49:52] [Server thread/INFO]: Stopping the server
[03:49:52] [Server thread/INFO]: Stopping server
[03:49:52] [Server thread/INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.1.12
[03:49:52] [Server thread/INFO]: [AACAdditionPro] Disabling AACAdditionPro v1.8.2
[03:49:52] [Server thread/INFO]: [AACAdditionPro] AACAdditionPro disabled.[m
[03:49:52] [Server thread/INFO]: [AACAdditionPro]  [m
[03:49:52] [Server thread/INFO]: [ServerSigns] Disabling ServerSigns v2.9.1
[03:49:52] [Server thread/INFO]: [ServerSigns] ServerSigns is now disabled.
[03:49:52] [Server thread/INFO]: [AAC] Disabling AAC v3.1.6
[03:49:52] [Server thread/INFO]: [AAC] Disabling checks...
[03:49:52] [Server thread/INFO]: [AAC] Saving log file...
[03:49:52] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.2.0
[03:49:52] [Server thread/INFO]: [KingKits] Disabling KingKits v5.2.9
[03:49:52] [Server thread/INFO]: [TitleManager] Disabling TitleManager v1.5.11

**Comment by campzazathelord** [comment] 2017-05-16 08:24
still getting this error in latest ver of aacadditionpro

**Comment by Photon-GitHub** [comment] 2017-05-19 13:39
Another duplicate of #74 .

**Closed by Photon-GitHub** 2017-05-19 13:39 UTC
Labels: error, insufficient information
