### ISSUE TITLE
Various Async Exceptions (PlayerAdditionViolationCommandEvent)

### ISSUE THREAD

**Issue by Puremin0rez** [Photon-GitHub/AACAdditionPro#363] opened 2020-01-05 01:53 UTC
https://pastebin.com/4ET3EvUA
https://pastebin.com/hU49wezs

Seems to be the same as #357 but doesn't appear to be fixed.

Minecraft 1.15.1 running AAC 4.3.4, AACAdditionPro 6.0.0, ProtocolLib 4.5.0.

**Comment by Keviro** [comment] 2020-01-05 17:26
I can confirm this on git-paper-33 (1.15.1)

https://pastebin.com/ytX9gsZ4

**Comment by Photon-GitHub** [comment] 2020-01-06 18:46
Duplicate of #362

**Closed by Photon-GitHub** 2020-01-06 18:46 UTC
