### ISSUE TITLE
Scoreboard Component?

### ISSUE THREAD

**Issue by MatheweB** [Photon-GitHub/AACAdditionPro#120] opened 2017-08-03 21:27 UTC
AAC addition pro is spamming these warn messages (this is the 250,000th WARN), and I'm not sure what is causing it. I have the latest weatherboard, recommended spigot lib, and aac/aacadditionpro.

I am also running minecraft 1.12.1

03.08 17:25:40 [Server] WARN [AACAdditionPro] Task #250409 for AACAdditionPro v3.0.2-b4 generated an exception
03.08 17:25:40 [Server] INFO java.lang.IllegalStateException: Unregistered scoreboard component
03.08 17:25:40 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:270) ~[spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 17:25:40 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftTeam.removeEntry(CraftTeam.java:172) ~[spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 17:25:40 [Server] INFO at de.photon.AACAdditionPro.aL.a(aL.java) ~[AACAdditionPro-3.0.2-b4.jar:?]
03.08 17:25:40 [Server] INFO at de.photon.AACAdditionPro.aH.lambda$new$0(aH.java) ~[AACAdditionPro-3.0.2-b4.jar:?]
03.08 17:25:40 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 17:25:40 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 17:25:40 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 17:25:40 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 17:25:40 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 17:25:40 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 17:25:40 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by OberlinMinecraft** [comment] 2017-08-04 00:27
Yes I do

**Comment by MatheweB** [comment] 2017-08-04 01:01
Yes I do

**Comment by Photon-GitHub** [comment] 2017-08-04 11:24
It is indeed caused by some scoreboard modification that my entities don't like.

**Comment by MatheweB** [comment] 2017-08-04 12:31
I have featherboard installed

**Comment by CeIebrimbor** [comment] 2017-08-04 14:24
Should not be related to Featherboard having an issue. It's the entities from AACaddition not playing nice with Mojang's lovely scoreboard/team system.

Disable that check for now and provide any new documentation you may have found leading up to disabling Killauraentities or AACaddition.

**Comment by Photon-GitHub** [comment] 2017-08-23 20:02
Should be fixed in 3.2.0-b1

**Closed by Photon-GitHub** 2017-08-23 20:02 UTC
Labels: error
